git submodule add https://github.com/karttur/geoimagine03-ktpandas ktpandas
git submodule add https://github.com/karttur/geoimagine03-userproj userproj
git submodule add https://github.com/karttur/geoimagine03-dem dem
git submodule add https://github.com/karttur/geoimagine03-setup_processes-x setup_processes
git submodule add https://github.com/karttur/geoimagine03-ktnumba ktnumba
git submodule add https://github.com/karttur/geoimagine03-grass grass
git submodule add https://github.com/karttur/geoimagine03-ktgdal ktgdal
git submodule add https://github.com/karttur/geoimagine03-zipper zipper
git submodule add https://github.com/karttur/geoimagine03-updatedb updatedb
git submodule add https://github.com/karttur/geoimagine03-basins basins
git submodule add https://github.com/karttur/geoimagine03-gis gis
git submodule add https://github.com/karttur/geoimagine03-landsat landsat
git submodule add https://github.com/karttur/geoimagine03-layout layout
git submodule add https://github.com/karttur/geoimagine03-projects projects
git submodule add https://github.com/karttur/geoimagine03-grace grace
git submodule add https://github.com/karttur/geoimagine03-smap smap
git submodule add https://github.com/karttur/geoimagine03-params params
git submodule add https://github.com/karttur/geoimagine03-timeseries timeseries
git submodule add https://github.com/karttur/geoimagine03-copernicus copernicus
git submodule add https://github.com/karttur/geoimagine03-setup_processes setup_processes
git submodule add https://github.com/karttur/geoimagine03-npproc npproc
git submodule add https://github.com/karttur/geoimagine03-ktgrass ktgrass
git submodule add https://github.com/karttur/geoimagine03-ancillary ancillary
git submodule add https://github.com/karttur/geoimagine03-sentinel sentinel
git submodule add https://github.com/karttur/geoimagine03-setup_db setup_db
git submodule add https://github.com/karttur/geoimagine03-extract extract
git submodule add https://github.com/karttur/geoimagine03-region region
git submodule add https://github.com/karttur/geoimagine03-modis modis
git submodule add https://github.com/karttur/geoimagine03-assets assets
git submodule add https://github.com/karttur/geoimagine03-support support
git submodule add https://github.com/karttur/geoimagine03-postgresdb postgresdb
git submodule add https://github.com/karttur/geoimagine03-export export
